// Copyright (c) 2018-2022 The MobileCoin Foundation

//! OpenTelemetry wrappers and helper utilities.

pub use opentelemetry::{
    global::BoxedTracer,
    trace::{mark_span_as_active, FutureExt, Span, SpanKind, TraceContextExt, Tracer},
    Context, Key, KeyValue,
};

use opentelemetry::{
    trace::{SpanBuilder, SpanId, TraceId},
    InstrumentationScope,
};
use opentelemetry_sdk::trace::{IdGenerator, RandomIdGenerator};
use std::{borrow::Cow, cell::Cell, time::SystemTime};
mod extractor;
mod injector;
mod otlp;

pub use extractor::extract_context;
pub use injector::InjectContext;
pub use otlp::{setup_default_tracer, setup_default_tracer_with_tags, telemetry_enabled, Error};

#[macro_export]
macro_rules! tracer {
    () => {
        $crate::versioned_tracer(
            env!("CARGO_PKG_NAME"),
            Some(env!("CARGO_PKG_VERSION")),
            None,
        )
    };
}

#[macro_export]
macro_rules! telemetry_static_key {
    ($key_name:tt) => {
        $crate::Key::from_static_str(concat!(
            "mobilecoin.com/",
            env!("CARGO_PKG_NAME"),
            "/",
            $key_name
        ))
    };
}

/// A magic value that is used as part of the predictable trace id generated by
/// `block_index_to_trace_id`. (Hex encoding of 'BLKID', chosen arbitrarily)
pub const BLOCK_INDEX_TRACE_ID_MAGIC: u128 = 0x424c4b4944;

thread_local! {
    static TRACE_ID_OVERRIDE: Cell<Option<TraceId>> = const { Cell::new(None) };
}

/// Generates random IDs unless a trace ID override has been supplied for the
/// next root span created on this thread.
#[derive(Debug, Default)]
pub(crate) struct BlockTraceIdGenerator(RandomIdGenerator);

impl IdGenerator for BlockTraceIdGenerator {
    fn new_trace_id(&self) -> TraceId {
        TRACE_ID_OVERRIDE
            .with(Cell::take)
            .unwrap_or_else(|| self.0.new_trace_id())
    }

    fn new_span_id(&self) -> SpanId {
        self.0.new_span_id()
    }
}

struct TraceIdOverrideGuard(Option<TraceId>);

impl Drop for TraceIdOverrideGuard {
    fn drop(&mut self) {
        TRACE_ID_OVERRIDE.with(|trace_id| trace_id.set(self.0));
    }
}

fn with_trace_id_override<T>(trace_id: TraceId, create_span: impl FnOnce() -> T) -> T {
    let previous = TRACE_ID_OVERRIDE.with(|current| current.replace(Some(trace_id)));
    let _guard = TraceIdOverrideGuard(previous);
    create_span()
}

// Wrapper around tracer_provider call so users of this lib do not need to
// use GlobalTraceProvider.
pub fn versioned_tracer(
    name: impl Into<Cow<'static, str>>,
    version: Option<&'static str>,
    schema_url: Option<&'static str>,
) -> BoxedTracer {
    let mut builder = InstrumentationScope::builder(name);
    if let Some(version) = version {
        builder = builder.with_version(version);
    }
    if let Some(schema_url) = schema_url {
        builder = builder.with_schema_url(schema_url);
    }
    opentelemetry::global::tracer_with_scope(builder.build())
}

/// Creates a context when an explicit context is required. Useful when tracing
/// inside an `async` method.
pub fn create_context<T>(tracer: &BoxedTracer, name: T) -> Context
where
    T: Into<Cow<'static, str>>,
{
    let span = tracer.start(name);
    Context::current_with_span(span)
}

/// A utility method to create a predictable trace ID out of a block index.
/// This is used to group traces by block index.
pub fn block_index_to_trace_id(block_index: u64) -> TraceId {
    // Generate a predictable trace id out of the block index.
    // Jaeger displays only the first 7 characters of a trace id and that's where we
    // want our block index to land. 7 hex characters represent 28 bits being
    // displayed, leaving us with 100 bits that need to go to to the right of it.
    // Each character represents 4 bits of the trace id.
    let id: u128 = (block_index as u128) << 100 | BLOCK_INDEX_TRACE_ID_MAGIC;
    TraceId::from_bytes(id.to_be_bytes())
}

/// A span builder that assigns a block-derived trace ID when starting a root
/// span.
pub struct BlockSpanBuilder {
    inner: SpanBuilder,
    trace_id: TraceId,
}

impl BlockSpanBuilder {
    /// Set the span's start time.
    pub fn with_start_time(self, start_time: SystemTime) -> Self {
        Self {
            inner: self.inner.with_start_time(start_time),
            trace_id: self.trace_id,
        }
    }

    /// Start the span with the configured block-derived trace ID.
    pub fn start<T: Tracer>(self, tracer: &T) -> T::Span {
        with_trace_id_override(self.trace_id, || self.inner.start(tracer))
    }
}

/// Create a span builder and attach the trace ID to a specific block index.
pub fn block_span_builder<T: Tracer>(
    tracer: &T,
    span_name: &'static str,
    block_index: u64,
) -> BlockSpanBuilder {
    BlockSpanBuilder {
        inner: tracer.span_builder(span_name).with_kind(SpanKind::Server),
        trace_id: block_index_to_trace_id(block_index),
    }
}

/// Start a span tied to a specific block index.
pub fn start_block_span<T: Tracer>(
    tracer: &T,
    span_name: &'static str,
    block_index: u64,
) -> T::Span {
    block_span_builder(tracer, span_name, block_index).start(tracer)
}

#[cfg(test)]
mod tests {
    use super::*;
    use opentelemetry::trace::TracerProvider;
    use opentelemetry_sdk::trace::SdkTracerProvider;

    #[test]
    fn block_spans_use_deterministic_trace_ids_without_affecting_other_spans() {
        let provider = SdkTracerProvider::builder()
            .with_id_generator(BlockTraceIdGenerator::default())
            .build();
        let tracer = provider.tracer("test");
        let block_index = 42;

        let block_span = start_block_span(&tracer, "block", block_index);
        assert_eq!(
            block_span.span_context().trace_id(),
            block_index_to_trace_id(block_index)
        );

        let ordinary_span = tracer.start("ordinary");
        assert_ne!(
            ordinary_span.span_context().trace_id(),
            block_index_to_trace_id(block_index)
        );
    }
}
