// Copyright (c) 2018-2021 The MobileCoin Foundation

//! A node of the consensus network.

#![allow(clippy::ptr_arg)] // Clippy is complaining about code generated by automock.

mod node_impl;
mod node_trait;

pub use node_impl::Node;
pub use node_trait::{MockScpNode, ScpNode};
