// Copyright (c) 2018-2023 The MobileCoin Foundation

//! mobilecoind gRPC API.

use mc_util_uri::{Uri, UriScheme};

mod autogenerated_code {
    // Expose proto data types from included third-party/external proto files.
    pub use mc_api::{blockchain, external, printable, watcher};
    pub use mc_fog_api::fog_ledger;

    pub mod mobilecoind_api {
        include!(concat!(
            env!("OUT_DIR"),
            "/protos-auto-gen/mobilecoind_api.rs"
        ));
    }
}

pub use autogenerated_code::{mobilecoind_api::*, *};

impl OutlayV2 {
    /// This is used for some tests
    pub fn new_from_outlay_and_token_id(outlay: &Outlay, token_id: u64) -> Self {
        Self {
            value: outlay.value,
            receiver: outlay.receiver.clone(),
            token_id,
            tx_private_key: outlay.tx_private_key.clone(),
        }
    }
}

pub type MobilecoindUri = Uri<MobilecoindScheme>;

/// Mobilecoind  Uri Scheme
#[derive(Debug, Hash, Ord, PartialOrd, Eq, PartialEq, Clone)]
pub struct MobilecoindScheme {}
impl UriScheme for MobilecoindScheme {
    /// The part before the '://' of a URL.
    const SCHEME_SECURE: &'static str = "mobilecoind";
    const SCHEME_INSECURE: &'static str = "insecure-mobilecoind";

    /// Default port numbers
    const DEFAULT_SECURE_PORT: u16 = 4443;
    const DEFAULT_INSECURE_PORT: u16 = 4444;
}
