// Copyright (c) 2018-2022 The MobileCoin Foundation

//! MobileCoin gRPC API.

mod autogenerated_code {
    // Expose proto data types from included third-party/external proto files.
    pub use mc_api::{blockchain, external};
    pub use mc_attest_api::attest;

    #[path = "consensus_client.rs"]
    pub mod consensus_client {
        include!(concat!(
            env!("OUT_DIR"),
            "/protos-auto-gen/consensus_client.rs"
        ));
    }
    #[path = "consensus_peer.rs"]
    pub mod consensus_peer {
        include!(concat!(
            env!("OUT_DIR"),
            "/protos-auto-gen/consensus_peer.rs"
        ));
    }
    #[path = "consensus_common.rs"]
    pub mod consensus_common {
        include!(concat!(
            env!("OUT_DIR"),
            "/protos-auto-gen/consensus_common.rs"
        ));
    }
    #[path = "consensus_config.rs"]
    pub mod consensus_config {
        include!(concat!(
            env!("OUT_DIR"),
            "/protos-auto-gen/consensus_config.rs"
        ));
    }
}

pub mod tonic {
    pub use mc_attest_api::tonic as attest;
    tonic::include_proto!("consensus_client");
    tonic::include_proto!("consensus_common");
    tonic::include_proto!("consensus_config");
    tonic::include_proto!("consensus_peer");
}

pub mod conversions;

pub use autogenerated_code::*;
pub use mc_api::ConversionError;
