// Copyright (c) 2018-2022 The MobileCoin Foundation

//! MobileCoin gRPC API.

mod autogenerated_code {
    // Expose proto data types from included third-party/external proto files.
    pub use mc_api::{blockchain, external};
    pub use mc_attest_api::attest;

    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}

pub mod conversions;

pub use autogenerated_code::*;
pub use mc_api::ConversionError;
