#!/bin/bash

# Copyright (c) 2018-2020 MobileCoin Inc.

set -ex
# The path to mobilecoin_api and wallet protos
MC_PROTO_PATH=$1
MOBILECOIND_API_PROTO_PATH=$2

python3 -m grpc_tools.protoc -I${MC_PROTO_PATH} -I${MOBILECOIND_API_PROTO_PATH} --python_out=. --grpc_python_out=. ${MOBILECOIND_API_PROTO_PATH}/mobilecoind_api.proto
python3 -m grpc_tools.protoc -I${MC_PROTO_PATH} -I${MOBILECOIND_API_PROTO_PATH} --python_out=. --grpc_python_out=. ${MC_PROTO_PATH}/external.proto
