[package]
name = "mc-sgx-compat"
version = "7.0.1"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
# TODO: Consider making sgx a self-contained workspace and get the value from there.
rust-version = "1.83.0"

[features]
# In default mode we depend on std, which is appropriate for `cargo test`
default = []
# In sgx mode we bring in sgx-only implementations
sgx = [
    'mc-sgx-alloc',
    'mc-sgx-alloc/oom_panic',
    'mc-sgx-panic',
    'mc-sgx-panic/panic_abort',
    'mc-sgx-sync',
    'mc-sgx-sync/mc-sgx-panic',
    'mc-sgx-debug',
    'mc-sgx-service',
]

# All dependencies are optional
[dependencies]
cfg-if = { workspace = true }
mc-sgx-alloc = { workspace = true, optional = true }
mc-sgx-debug = { workspace = true, optional = true }
mc-sgx-panic = { workspace = true, optional = true }
mc-sgx-service = { workspace = true, optional = true }
mc-sgx-sync = { workspace = true, optional = true }
mc-sgx-types = { workspace = true }
