// Copyright (c) 2018-2021 The MobileCoin Foundation

//! MobileCoin gRPC API.

#![feature(custom_test_frameworks)]
#![test_runner(datatest::runner)]

mod autogenerated_code {
    pub use protobuf::well_known_types::Empty;

    // Needed due to how to the auto-generated code references the Empty message.
    pub mod empty {
        pub use protobuf::well_known_types::Empty;
    }

    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}
mod convert;

pub mod display;

pub use autogenerated_code::*;
pub use convert::*;
