// Copyright (c) 2018-2020 MobileCoin Inc.

//! MobileCoin gRPC API.

mod autogenerated_code {
    pub use protobuf::well_known_types::Empty;

    // Needed due to how to the auto-generated code references the Empty message.
    pub mod empty {
        pub use protobuf::well_known_types::Empty;
    }

    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}

pub mod conversions;
pub mod display;

pub use autogenerated_code::*;
pub use conversions::ConversionError;
