// Copyright (c) 2018-2022 The MobileCoin Foundation

//! MobileCoin gRPC API.

#![warn(unused_extern_crates)]

mod autogenerated_code {
    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}
mod convert;

pub mod display;

pub use crate::{autogenerated_code::*, convert::*};
