// Copyright (c) 2018-2022 The MobileCoin Foundation

#![no_std]

//! This crate implements a simple authenticated public-key crypto API, for
//! messages of arbitrary length.
//! - Ristretto Curvepoints used for ECDH
//! - HKDF<Blake2b> used to extract key material from dh_shared_secret
//! - Aes-128-Gcm used to encrypt and mac the payload
//!
//! There is also a versioning tag used to allow for a wire-stable format
//!
//! To use, create the object `VersionedCryptoBox`, then use the CryptoBox trait
//! to encrypt and decrypt.

extern crate alloc;

mod hkdf_box;
mod traits;
mod versioned;

pub use generic_array;
pub use mc_oblivious_aes_gcm::aead::{self, Error as AeadError};
pub use traits::{CryptoBox, Error};
pub use versioned::{VersionError, VersionedCryptoBox};

// FixedBuffer allows to use a &mut [u8] slice as a fixed-capacity aead::Buffer
mod fixed_buffer;
pub use fixed_buffer::FixedBuffer;

#[cfg(test)]
mod test {
    use super::*;
    use generic_array::arr;
    use hex_literal::hex;
    use mc_crypto_keys::{RistrettoPrivate, RistrettoPublic};
    use mc_util_from_random::FromRandom;
    use mc_util_test_helper::{RngType, SeedableRng};

    extern crate mc_util_test_helper;

    #[test]
    fn test_pre_upgrade_wire_compatibility() {
        // Generated by VersionedCryptoBox at commit b3582c6cc, using aead 0.5
        // and mc-oblivious-aes-gcm 0.10.1, with:
        //
        // let recipient_private = RistrettoPrivate::from_bytes_mod_order(&[42; 32]);
        // let recipient_public = RistrettoPublic::from(&recipient_private);
        // let mut rng = RngType::from_seed([7; 32]);
        // let cryptogram = VersionedCryptoBox::default()
        //     .encrypt(&mut rng, &recipient_public, b"wire-stable")
        //     .unwrap();
        const PLAINTEXT: &[u8] = b"wire-stable";
        const CRYPTOGRAM: [u8; 61] = hex!(
            "42ef569fd40d5578c4f760988cf59479686cb29ad67dbd35e8233e6c495ffcba"
            "b96368659e1a2422bc730f000af4b9928efe7ba87ef7b0957b22970100"
        );

        let recipient_private = RistrettoPrivate::from_bytes_mod_order(&[42; 32]);
        let recipient_public = RistrettoPublic::from(&recipient_private);

        let (success, decrypted) = VersionedCryptoBox::default()
            .decrypt(&recipient_private, &CRYPTOGRAM)
            .expect("pre-upgrade cryptogram should decrypt");
        assert!(bool::from(success));
        assert_eq!(decrypted, PLAINTEXT);

        let mut rng = RngType::from_seed([7; 32]);
        let encrypted = VersionedCryptoBox::default()
            .encrypt(&mut rng, &recipient_public, PLAINTEXT)
            .expect("encryption should succeed");
        assert_eq!(encrypted, CRYPTOGRAM);
    }

    #[test]
    fn test_round_trip() {
        let algo = VersionedCryptoBox::default();
        let plaintext1 = b"01234567".to_vec();
        let plaintext2 = plaintext1.repeat(50);

        mc_util_test_helper::run_with_several_seeds(|mut rng| {
            let a = RistrettoPrivate::from_random(&mut rng);
            let a_pub = RistrettoPublic::from(&a);

            for plaintext in &[&plaintext1[..], &plaintext2[..]] {
                for _reps in 0..50 {
                    let ciphertext = algo.encrypt(&mut rng, &a_pub, plaintext).unwrap();
                    let (success, decrypted) =
                        algo.decrypt(&a, &ciphertext).expect("decryption failed!");
                    assert_eq!(plaintext.len(), decrypted.len());
                    assert_eq!(plaintext, &&decrypted[..]);
                    assert!(bool::from(success));
                }
            }
        });
    }

    #[test]
    fn test_expected_failure() {
        let algo = VersionedCryptoBox::default();
        let plaintext1 = b"01234567".to_vec();
        let plaintext2 = plaintext1.repeat(50);

        mc_util_test_helper::run_with_several_seeds(|mut rng| {
            let a = RistrettoPrivate::from_random(&mut rng);
            let a_pub = RistrettoPublic::from(&a);

            let not_a = RistrettoPrivate::from_random(&mut rng);

            for plaintext in &[&plaintext1[..], &plaintext2[..]] {
                for _reps in 0..50 {
                    let ciphertext = algo.encrypt(&mut rng, &a_pub, plaintext).unwrap();
                    let (success, _decrypted) = algo.decrypt(&not_a, &ciphertext).unwrap();
                    assert!(!bool::from(success));
                }
            }
        });
    }

    #[test]
    fn test_round_trip_fixed_length() {
        let algo = VersionedCryptoBox::default();
        let plaintext1 = arr![u8; 0, 1, 2, 3, 4, 4, 3, 2];
        let plaintext2 = arr![u8; 42, 42, 42, 42, 78, 78, 78, 78];

        mc_util_test_helper::run_with_several_seeds(|mut rng| {
            let a = RistrettoPrivate::from_random(&mut rng);
            let a_pub = RistrettoPublic::from(&a);

            for plaintext in &[plaintext1, plaintext2] {
                for _reps in 0..10 {
                    let ciphertext = algo
                        .encrypt_fixed_length(&mut rng, &a_pub, plaintext)
                        .unwrap();
                    let (success, decrypted) = algo
                        .decrypt_fixed_length(&a, &ciphertext)
                        .expect("decryption failed!");
                    assert_eq!(plaintext, &decrypted);
                    assert!(bool::from(success));
                }
            }
        });
    }
}
