// Copyright (c) 2018-2022 The MobileCoin Foundation

//! A gRPC API module for attestation

mod autogenerated_code {
    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}

pub mod conversions;
pub use autogenerated_code::*;
