// Copyright (c) 2018-2022 The MobileCoin Foundation

//! MobileCoin Ledger Streaming API.

mod autogenerated_code {
    use mc_api::{blockchain, external};

    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}
mod convert;
mod error;
mod traits;

pub use self::{
    autogenerated_code::*,
    convert::*,
    error::{Error, Result},
    traits::BlockSource,
};
