# Copyright (c) 2018-2022 The MobileCoin Foundation
#
# Dockerfile.fog-test-client
#
# Binaries and associated tools for running fog-test-client in canary mode for continuous
# e2e testing.

ARG REPO_ORG=mobilecoin
FROM ${REPO_ORG}/runtime-base:latest

RUN addgroup --system --gid 1000 app \
  && addgroup --system --gid 2000 app-data \
  && adduser --system --ingroup app --uid 1000 app \
  && usermod -a -G 2000 app

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y ca-certificates \
  && apt-get clean \
  && rm -r /var/lib/apt/lists

# Copy binaries
ARG RUST_BIN_PATH=target/release
COPY ${RUST_BIN_PATH}/test_client /usr/local/bin/
COPY ${RUST_BIN_PATH}/mc-admin-http-gateway /usr/local/bin/
COPY ${RUST_BIN_PATH}/mc-util-grpc-token-generator /usr/local/bin/

# Entrypoint
COPY .internal-ci/docker/entrypoints/fog-test-client.sh /usr/local/bin/entrypoint.sh

ENV KEY_DIR /keys
ENV MC_CONSENSUS_ENCLAVE_CSS /measurements/consensus-enclave.css
ENV MC_INGEST_ENCLAVE_CSS /measurements/ingest-enclave.css
ENV MC_LEDGER_ENCLAVE_CSS /measurements/ledger-enclave.css
ENV MC_VIEW_ENCLAVE_CSS /measurements/view-enclave.css
ENV MC_ADMIN_LISTEN_URI insecure-mca://0.0.0.0:8001/
ENV MC_TRANSFER_AMOUNT 100000000000
ENV MC_CONTINUOUS true
ENV MC_TRANSFER_PERIOD 60
ENV MC_CONSENSUS_WAIT 15
ENV MC_NUM_CLIENTS 4
ENV MC_NO_MEMOS true

# Required Environment Variables
# MC_CONSENSUS_VALIDATORS - comma separated list of consensus urls.
# MC_FOG_VIEW - fog view url.
# MC_FOG_LEDGER - fog ledger url.
# MC_CLIENT_AUTH_TOKEN_SECRET - if running against a Signal fog instance.

# Share key files in /keys
VOLUME /keys
# Share enclave css files in /measurements
VOLUME /measurements

USER app
EXPOSE 8001
ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]
CMD [ "/usr/local/bin/test_client" ]
