# Copyright (c) 2018-2022 The MobileCoin Foundation
#
# Dockerfile.go-grpc-gateway
#
# Runtime Image for the json -> grpc gateway service.

ARG REPO_ORG=mobilecoin
ARG BASE_TAG=latest
FROM ubuntu:jammy=20240227

ARG GO_BIN_PATH=go-grpc-gateway
COPY ${GO_BIN_PATH}/go-grpc-gateway /usr/bin/go-grpc-gateway

COPY .internal-ci/docker/entrypoints/go-grpc-gateway.sh /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]

EXPOSE 8000
