// Copyright (c) 2018-2023 MobileCoin, Inc.

//! T3 gRPC API.

use mc_util_uri::{Uri, UriScheme};

mod autogenerated_code {
    pub mod t3_v1 {
        include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/t3.v1.rs"));
    }
    pub mod external {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/external.v1.rs"));
        }
    }
}

pub use autogenerated_code::{t3_v1::*, *};

pub type T3Uri = Uri<T3Scheme>;

/// T3 Uri Scheme
#[derive(Debug, Hash, Ord, PartialOrd, Eq, PartialEq, Clone)]
pub struct T3Scheme {}
impl UriScheme for T3Scheme {
    /// The part before the '://' of a URL.
    const SCHEME_SECURE: &'static str = "t3";
    const SCHEME_INSECURE: &'static str = "insecure-t3";

    /// Default port numbers
    const DEFAULT_SECURE_PORT: u16 = 443;
    const DEFAULT_INSECURE_PORT: u16 = 8080;
}
