[package]
name = "mc-util-telemetry"
version = "7.0.1"
authors = ["MobileCoin"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
rust-version = { workspace = true }

[features]
jaeger = ["dep:opentelemetry-jaeger"]

[lib]
path = "src/lib.rs"

[dependencies]
cfg-if = { workspace = true }
displaydoc = { workspace = true }
hostname = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-jaeger = { workspace = true, features = ["reqwest_rustls_collector_client"], optional = true }
opentelemetry_sdk = { workspace = true }
