# Copyright (c) 2018-2022 The MobileCoin Foundation
#
# MobileCoin Core projects - Dispatch (manual) Job - Delete target dev env components and optionally the k8s namespace.

name: (Manual) Delete a Dev Namespace

run-name: Reset and Delete ${{ inputs.namespace }}

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      domain_name:
        description: "Domain name for ingress hosts"
        type: string
        required: false
        default: development.mobilecoin.com

jobs:
  reset:
    name: Reset Dev Namespace - ${{ inputs.namespace }}
    uses: ./.github/workflows/mobilecoin-workflow-dev-reset.yaml
    with:
      namespace: ${{ inputs.namespace }}
      domain_name: ${{ inputs.domain_name }}
    secrets: inherit
